[package]
name = "rust-conway"
version = "0.1.0"
authors = ["Ludmila Shako <ludmila.shako@qliro.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.6"
rand = "0.8.0"
structopt = "0.3"